FROM golang:alpine

MAINTAINER Ryan Smith

RUN apk add --no-cache vim
RUN apk add --no-cache git

#Install biogo packages
RUN go get github.com/biogo/biogo/...
RUN go get github.com/biogo/hts/...
RUN go get github.com/biogo/graphics/...
RUN go get github.com/biogo/ncbi/...
RUN go get github.com/biogo/store/...
RUN go get github.com/biogo/external/...
RUN go get github.com/biogo/ragel/...
RUN go get github.com/biogo/rnaseq/...
RUN go get github.com/biogo/illumina/...
RUN go get github.com/biogo/graph/...
RUN go get github.com/biogo/cluster/...

